#define PREFIX TF47

#define WHITELIST_USER_ADMIN 1
#define WHITELIST_USER_MODERATOR 2
#define WHITELIST_USER_TF 3
#define WHITELIST_CCT 4
#define WHITELIST_HELO 5
#define WHITELIST_PLANE 6
#define WHITELIST_ATTACK_AIR 7
#define WHITELIST_UAV 8
#define WHITELIST_TANK 9
#define WHITELIST_BUILDERS 10

#define EVENT_PLAYER_UNCON 1
#define EVENT_PLAYER_DEAD 2
#define EVENT_PLAYER_HEAL 3
#define EVENT_PLAYER_BAD_WEAPON 4

#define EVENT_VEHICLE_DESTROYED_CAR 5
#define EVENT_VEHICLE_DESTROYED_TANK 6
#define EVENT_VEHICLE_DESTROYED_HELO 7
#define EVENT_VEHICLE_DESTROYED_PLANE 8

#define EVENT_CIVILIAN_DEAD 10
#define EVENT_HOUSE_DESTROYED 11

#define EVENT_OBJECTIVE_STARTED 20
#define EVENT_OBJECTIVE_FAILED 21
#define EVENT_OBJECTIVE_COMPLETED 22