#define PREFIX TF47

#define WHITELIST_USER_ADMIN 1
#define WHITELIST_USER_MODERATOR 2
#define WHITELIST_USER_TF 3
#define WHITELIST_CCT 4
#define WHITELIST_HELO 5
#define WHITELIST_PLANE 6
#define WHITELIST_UAV 7
#define WHITELIST_TANK 8
#define WHITELIST_BUILDERS 9
#define WHITELIST_ISMODERATOR 10
#define WHITELIST_ISADMIN 11